# Generated by Django 3.1.1 on 2021-03-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=32, verbose_name='订单号')),
                ('sports_type', models.CharField(max_length=16, verbose_name='场地类型')),
                ('order_date', models.DateField(verbose_name='订单时间')),
                ('booking_date', models.DateField(verbose_name='预订时间')),
                ('booking_weekday', models.IntegerField(verbose_name='订单星期数')),
                ('order_coordinate', models.CharField(max_length=32, verbose_name='预订场地')),
                ('payment', models.IntegerField(verbose_name='应付金额')),
                ('order_status', models.BooleanField(verbose_name='订单状态')),
                ('fail_cause', models.CharField(max_length=32, verbose_name='失败原因')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
            ],
            options={
                'db_table': 'order_profile',
            },
        ),
    ]
