# Generated by Django 3.1.1 on 2021-03-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbooking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderprofile',
            name='fail_cause',
        ),
        migrations.AddField(
            model_name='orderprofile',
            name='is_use_free',
            field=models.BooleanField(default=0, verbose_name='是否使用免费次数'),
        ),
        migrations.AlterField(
            model_name='orderprofile',
            name='order_status',
            field=models.BooleanField(default=0, verbose_name='订单状态'),
        ),
    ]
