# Generated by Django 3.1.1 on 2021-03-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbooking', '0002_auto_20210330_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderprofile',
            name='payment_status',
            field=models.BooleanField(default=0, verbose_name='支付状态'),
        ),
    ]
