# Generated by Django 3.1.1 on 2021-03-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbooking', '0003_orderprofile_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderprofile',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
