# Generated by Django 3.1.1 on 2021-03-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbooking', '0006_auto_20210330_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderprofile',
            name='order_date',
            field=models.DateTimeField(verbose_name='订单时间'),
        ),
    ]
