# Generated by Django 3.1.1 on 2021-03-31 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbooking', '0009_auto_20210331_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderprofile',
            name='payment',
            field=models.FloatField(null=True, verbose_name='应付金额'),
        ),
    ]
