# Generated by Django 3.1.1 on 2021-04-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbooking', '0010_auto_20210331_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderprofile',
            name='order_status',
            field=models.CharField(default='unstarted', max_length=32, verbose_name='订单状态'),
        ),
    ]
