# Generated by Django 3.1.1 on 2021-04-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbooking', '0011_auto_20210408_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackUpOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(null=True, verbose_name='预订时间')),
                ('booking_weekday', models.IntegerField(null=True, verbose_name='订单星期数')),
                ('order_coordinate', models.CharField(max_length=32, null=True, verbose_name='预订场地')),
            ],
        ),
    ]
