# Generated by Django 3.1.1 on 2021-04-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbooking', '0012_backuporder'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuporder',
            name='backup_user',
            field=models.CharField(max_length=12, null=True, verbose_name='学号'),
        ),
        migrations.AddField(
            model_name='backuporder',
            name='compensate_to',
            field=models.CharField(max_length=32, null=True, verbose_name='补偿用户'),
        ),
        migrations.AlterModelTable(
            name='backuporder',
            table='backup_order',
        ),
    ]
