# Generated by Django 3.1.1 on 2021-04-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbooking', '0013_auto_20210408_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backuporder',
            name='booking_weekday',
        ),
        migrations.AddField(
            model_name='backuporder',
            name='backuo_portal_pass',
            field=models.CharField(max_length=32, null=True, verbose_name='门户密码'),
        ),
    ]
