# Generated by Django 3.1.1 on 2021-04-10 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbooking', '0014_auto_20210410_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backuporder',
            old_name='backuo_portal_pass',
            new_name='backup_portal_pass',
        ),
    ]
