# Generated by Django 3.1.1 on 2021-04-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbooking', '0017_auto_20210410_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuporder',
            name='backup_user_payment',
            field=models.CharField(max_length=32, null=True, verbose_name='支付方式'),
        ),
    ]
