# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-08-08 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=11, verbose_name='用户名')),
                ('gender', models.CharField(max_length=4, null=True, verbose_name='性别')),
                ('uni', models.CharField(default='', max_length=32, verbose_name='毕业/就读院校')),
                ('fach', models.CharField(default='', max_length=32, verbose_name='专业/职业')),
                ('class_num', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='等级')),
                ('mobile', models.CharField(max_length=14, unique=True, verbose_name='手机号')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('sign', models.CharField(default='', max_length=100, verbose_name='个人签名')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('avatar', models.ImageField(default='', upload_to='avatar', verbose_name='头像')),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
