# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-08-19 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='login_time',
            field=models.DateTimeField(default='1970-01-01 00:00:00', verbose_name='登录时间'),
        ),
    ]
