# Generated by Django 3.1.1 on 2021-02-28 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_login_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='sign',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_time',
        ),
    ]
