# Generated by Django 3.1.1 on 2021-03-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210310_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(max_length=14, null=True, verbose_name='手机号'),
        ),
    ]
