# Generated by Django 3.1.1 on 2021-03-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210315_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(max_length=14, verbose_name='手机号'),
        ),
    ]
