# Generated by Django 3.1.1 on 2021-03-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20210316_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=32, null=True, unique=True, verbose_name='邮箱'),
        ),
    ]
