# Generated by Django 3.1.1 on 2021-03-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20210316_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(max_length=14, unique=True, verbose_name='手机号'),
        ),
    ]
