# Generated by Django 3.1.1 on 2021-03-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20210316_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(max_length=14, null=True, verbose_name='手机号'),
        ),
    ]
