# Generated by Django 3.1.1 on 2021-03-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20210318_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='portal_pass',
            field=models.CharField(max_length=32, null=True, verbose_name='门户密码'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='student_no',
            field=models.CharField(max_length=12, null=True, verbose_name='学号'),
        ),
    ]
