# Generated by Django 3.1.1 on 2021-03-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20210326_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='student_no',
            field=models.CharField(default='unverified', max_length=12, verbose_name='学号'),
        ),
    ]
