# Generated by Django 3.1.1 on 2021-03-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20210326_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='free_times',
            field=models.FloatField(default=0.0, verbose_name='免费次数'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='invitation_code',
            field=models.CharField(max_length=32, null=True, verbose_name='邀请码'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_blocked',
            field=models.BooleanField(default=0, verbose_name='是否黑名单'),
        ),
    ]
