# Generated by Django 3.1.1 on 2021-04-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20210331_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackUpUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_no', models.CharField(max_length=12, null=True, verbose_name='学号')),
                ('portal_pass', models.CharField(max_length=32, null=True, verbose_name='门户密码')),
            ],
            options={
                'db_table': 'backup_user',
            },
        ),
    ]
